site_name: "ZenAI Programming Rituals"
site_description: Transform your AI assistant from a frustrating bot to a reliable programming partner
site_author: Nauman
repo_name: inauman/zenai-programming-rituals
repo_url: https://github.com/inauman/zenai-programming-rituals

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  font:
    text: Roboto
    code: Roboto Mono
  logo: false
  favicon: false

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/inauman/zenai-programming-rituals 